# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build live-chat-api`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t live-chat-api`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system live-chat-api && \
          adduser --system -G live-chat-api live-chat-api

COPY dist/live-chat-api live-chat-api
RUN chown -R live-chat-api:live-chat-api .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix live-chat-api --omit=dev -f install

CMD [ "node", "live-chat-api" ]
